# -*- coding: utf-8 -*-
"""
Generate Markdown Report for Floodzy Feature Importance Analysis.

Script ini membuat laporan akademik otomatis dari hasil analisis feature importance
yang sudah dihasilkan oleh XGBoost dan SHAP.

Output: reports/feature_importance/Feature_Importance_Floodzy_Report.md

Author: Gemini AI for Floodzy Project
Date: 21 Oktober 2025
"""

import os
import pandas as pd
from datetime import datetime

# --- 1. Path konfigurasi ---
REPORT_DIR = "reports/feature_importance"
CSV_PATH = os.path.join(REPORT_DIR, "shap_feature_importance_values.csv")
XGB_IMG = os.path.join(REPORT_DIR, "xgb_feature_importance_top10.png")
SHAP_IMG = os.path.join(REPORT_DIR, "shap_summary_plot.png")
OUTPUT_PATH = os.path.join(REPORT_DIR, "Feature_Importance_Floodzy_Report.md")

def generate_markdown():
    """Buat laporan Markdown otomatis berdasarkan hasil CSV + visualisasi."""
    print("📄 Membuat laporan Markdown untuk Floodzy Feature Importance...")

    if not os.path.exists(CSV_PATH):
        raise FileNotFoundError(f"Tidak ditemukan file hasil analisis: {CSV_PATH}")

    df = pd.read_csv(CSV_PATH)
    df_sorted = df.sort_values("importance", ascending=False)
    top5 = df_sorted.head(5)
    top_feature = top5.iloc[0]["feature"]

    # --- 2. Struktur konten laporan ---
    now = datetime.now().strftime("%d %B %Y, %H:%M WIB")

    content = f"""# 📊 Laporan Analisis Feature Importance Floodzy  
*Dibuat otomatis oleh Gemini AI — {now}*  

---

## 1️⃣ Pendahuluan

Analisis ini bertujuan untuk memahami **faktor-faktor utama yang memengaruhi prediksi banjir**
pada model **XGBoost Floodzy**. Dua pendekatan yang digunakan:

- **XGBoost Feature Importance (Gain):** Mengukur kontribusi relatif fitur terhadap performa model.  
- **SHAP (SHapley Additive Explanations):** Memberikan interpretasi mendalam mengenai arah dan besaran pengaruh fitur.

---

## 2️⃣ Visualisasi Utama

### 📈 XGBoost Top 10 Feature Importance
![XGBoost Importance]({XGB_IMG})

### 🔵 SHAP Summary Plot
![SHAP Summary]({SHAP_IMG})

---

## 3️⃣ Lima Fitur Paling Berpengaruh

| Ranking | Nama Fitur | Skor Pengaruh (Mean |SHAP|) |
|----------|-------------|----------------------|
"""

    for i, row in enumerate(top5.itertuples(index=False), start=1):
        content += f"| {i} | {row.feature} | {row.importance:.6f} |\n"

    content += f"""

Dari hasil di atas, fitur **`{top_feature}`** menunjukkan pengaruh paling dominan
dalam menentukan kemungkinan terjadinya banjir.

---

## 4️⃣ Interpretasi dan Insight

- Fitur dengan nilai SHAP tinggi menunjukkan **kontribusi besar** terhadap hasil prediksi model.  
- Warna **merah** pada grafik SHAP menunjukkan nilai fitur yang tinggi (cenderung meningkatkan peluang banjir).  
- Warna **biru** menunjukkan nilai fitur rendah (cenderung menurunkan peluang banjir).  
- Kombinasi XGBoost dan SHAP memberikan validasi yang kuat terhadap konsistensi model.

---

## 5️⃣ Kesimpulan Akademik

1. Model **XGBoost Floodzy** terbukti mampu mengidentifikasi fitur-fitur yang relevan secara konsisten.  
2. Fitur **`{top_feature}`** menjadi faktor paling penting dan dapat digunakan sebagai **indikator utama peringatan dini banjir**.  
3. Analisis ini dapat digunakan untuk **mendukung laporan penelitian, skripsi, maupun publikasi akademik**.

---

## 📚 Rekomendasi Lanjutan

- **Retraining Model:** Sertakan data tahun terbaru untuk menjaga robustnes model.  
- **Monitoring Drift:** Lakukan validasi temporal setiap 3–6 bulan.  
- **Integrasi Dashboard:** Gunakan hasil SHAP ini sebagai bagian dari sistem monitoring Floodzy.

---

**Generated by Floodzy ML System (Gemini AI Edition)**  
🕒 *{now}*  
"""

    # --- 3. Simpan hasil laporan ---
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"✅ Laporan Markdown berhasil dibuat di: {OUTPUT_PATH}")


if __name__ == "__main__":
    generate_markdown()
